import Image from'next/image';import Link from'next/link';import{ArrowRight,Building2,Gift,HeartHandshake,PackageCheck,ShieldCheck,Sparkles,Truck}from'lucide-react';import type{HomepageSection,Product}from'@/lib/types';import{ProductCard}from'./product-card';import{Reveal}from'./reveal';
const recipients=[['For Her','#f7d8dc','♥'],['For Him','#dce8f1','✦'],['For Couples','#eadff2','∞'],['For Parents','#f4e2cc','⌂'],['For Bestie','#f4dcea','☺'],['For Kids','#dbeee5','★']];
export function HomepageSections({sections,products}:{sections:HomepageSection[];products:Product[]}){return <>{sections.filter(s=>s.enabled).sort((a,b)=>a.sortOrder-b.sortOrder).map(section=><HomepageSectionView key={section.id} section={section} products={products}/>)}</>}
function HomepageSectionView({section,products}:{section:HomepageSection;products:Product[]}){switch(section.type){case'hero_slider':return <section className="hero shell" aria-labelledby="hero-title"><Image src="/giftmitra-hero.png" alt="A premium GiftMitra celebration box" fill priority sizes="(max-width:800px) 100vw,1240px"/><div className="hero-overlay"/><div className="hero-copy"><span className="eyebrow"><Sparkles/> {section.subtitle??'THE CELEBRATION EDIT'}</span><h1 id="hero-title">The art of making<br/><em>someone’s day.</em></h1><p>Beautifully curated gifts and personalised hampers, made for every kind of love.</p><div className="hero-actions"><Link href="/shop" className="button button-primary">Find the perfect gift <ArrowRight/></Link><Link href="/hamper-builder" className="text-link">Build your own hamper <ArrowRight/></Link></div><div className="hero-proof"><span>4.9 ★</span><span>Loved by thoughtful gifters</span><span>Secure checkout</span></div></div></section>;
case'recipient_collection':return <Reveal><section className="section shell"><div className="section-heading centered"><span className="eyebrow">GIFTING MADE PERSONAL</span><h2>{section.title}</h2><p>{section.subtitle??'Start with them. We’ll help with the magic.'}</p></div><div className="recipient-grid">{recipients.map(([name,color,mark])=><Link href={`/recipient/${name.toLowerCase().replaceAll(' ','-')}`} className="recipient-card" key={name}><span className="recipient-art" style={{background:color}}><span>{mark}</span></span><strong>{name}</strong><small>Thoughtfully chosen</small></Link>)}</div></section></Reveal>;
case'product_grid':return <Reveal><section className="section product-section"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">MOST-LOVED GIFTS</span><h2>{section.title}</h2><p>{section.subtitle??'Thoughtful, beautiful and ready to make their day.'}</p></div><Link href="/shop" className="text-link">View all gifts <ArrowRight/></Link></div><div className="product-grid">{products.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></div></section></Reveal>;
case'occasion_collection':return <Reveal><section className="section shell"><div className="section-heading centered"><span className="eyebrow">MOMENTS WORTH CELEBRATING</span><h2>{section.title}</h2></div><div className="occasion-banners">{['Birthday','Anniversary','Wedding','Just because'].map((o,i)=><Link href={`/occasion/${o.toLowerCase().replaceAll(' ','-')}`} key={o} style={{background:['#f5dadd','#dae6ee','#e8ddeb','#f1e1ce'][i]}}><span>0{i+1}</span><Gift/><h3>{o}</h3><small>Explore gifts →</small></Link>)}</div></section></Reveal>;
case'price_collection':return <Reveal><section className="price-section section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">BEAUTIFUL AT EVERY BUDGET</span><h2>{section.title}</h2></div><div>{[499,999,1499,2499].map((p,i)=><Link key={p} href={`/shop?maxPrice=${p}`}><span>{['Little joys','Thoughtful favourites','Extra special','The grand gesture'][i]}</span><b>Under ₹{p}</b><ArrowRight/></Link>)}</div></div></section></Reveal>;
case'custom_hamper':return <Reveal><section className="hamper-banner shell"><div><span className="eyebrow"><Sparkles/>MADE BY YOU</span><h2>{section.title}</h2><p>Choose the box, handpick every goodie, add their name and write from the heart.</p><Link href="/hamper-builder" className="button button-primary">Build a one-of-one hamper <ArrowRight/></Link></div><div className="hamper-banner-art"><span><Gift/></span><i>+ chocolates</i><i>+ candle</i><i>+ keepsake</i></div></section></Reveal>;
case'corporate_gifting':return <Reveal><section className="corporate-home"><div className="shell"><div><span className="eyebrow">CORPORATE, BUT NEVER COLD</span><h2>{section.title}</h2><p>Brand-right gifting for employees, clients and milestone moments—curated, customised and delivered across India.</p><Link href="/corporate-gifting" className="button button-primary">Explore corporate gifting</Link></div><div className="corporate-mini-grid">{[Building2,PackageCheck,Truck,HeartHandshake].map((Icon,i)=><span key={i}><Icon/><b>{['Custom branding','Scale-ready','Pan-India','Human support'][i]}</b></span>)}</div></div></section></Reveal>;
case'testimonials':return <Reveal><section className="section testimonial-section shell"><div className="section-heading centered"><span className="eyebrow">LOVE, DELIVERED</span><h2>{section.title}</h2></div><div><blockquote>“The hamper looked even more beautiful in person. Every detail felt warm, polished and truly personal.”<cite>— Aanya, Bengaluru · Verified customer</cite></blockquote><blockquote>“From 300 addresses to custom sleeves, the team made our festive gifting remarkably smooth.”<cite>— People team, Mumbai</cite></blockquote></div></section></Reveal>;
case'usp':return <section className="usp-strip"><div className="shell">{[[ShieldCheck,'Payments verified','Secure gateway confirmation'],[Gift,'Beautifully packed','Every unboxing matters'],[Truck,'Delivery clarity','Pincode-based estimates'],[HeartHandshake,'Human support','Real help when needed']].map(([Icon,title,text])=><span key={String(title)}><Icon/><b>{String(title)}</b><small>{String(text)}</small></span>)}</div></section>;
case'newsletter':return <section className="newsletter-section"><div><Sparkles/><span className="eyebrow">A LITTLE JOY IN YOUR INBOX</span><h2>{section.title}</h2><p>Fresh gifting ideas and members-only surprises. No clutter.</p><form action="/api/newsletter" method="post"><input name="email" type="email" required placeholder="Your email address"/><button>Join the joy →</button></form></div></section>;
default:return null}}
