import type { HomepageSection,Product } from './types';
/** Development-only preview data. Production reads the same shape from Supabase. */
export const demoProducts:Product[]=[
{id:'a1',slug:'rosy-glow-gift-box',name:'The Rosy Glow Gift Box',shortDescription:'A radiant edit of chocolate, candle and keepsake jewellery.',description:'A beautifully layered celebration box designed to create a true unboxing moment.',sku:'GM-RG-001',price:1499,mrp:1899,stock:18,rating:4.9,reviewCount:128,category:'Hampers',recipients:['For Her','Best Friend'],occasions:['Birthday','Anniversary'],badges:['Bestseller'],personalized:true,color:'#efd4d6',images:['/giftmitra-hero.png'],whatsInside:['Artisanal chocolates','Vanilla blush candle','Rose-gold bracelet','Personalised gift note']},
{id:'a2',slug:'quiet-luxury-hamper',name:'Quiet Luxury Hamper',shortDescription:'A serene edit for those who cherish the finer details.',description:'Understated luxury in a reusable magnetic box with handpicked self-care favourites.',sku:'GM-QL-002',price:2199,mrp:2799,stock:9,rating:4.8,reviewCount:86,category:'Luxury Hampers',recipients:['For Her','For Him'],occasions:['Anniversary','Wedding'],badges:['New'],personalized:false,color:'#e7d8cd',images:['/giftmitra-hero.png'],whatsInside:['Premium candle','Gourmet truffles','Fragrance mist','Keepsake card']},
{id:'a3',slug:'love-you-more-keepsake',name:'Love You More Keepsake',shortDescription:'A personalised memory made to stay.',description:'Turn a favourite photograph and message into a keepsake they will treasure.',sku:'GM-LM-003',price:899,mrp:1199,stock:25,rating:4.7,reviewCount:64,category:'Personalised Gifts',recipients:['For Couples','For Her'],occasions:['Anniversary','Valentine'],badges:['Personalise'],personalized:true,color:'#ead8e9',images:['/giftmitra-hero.png'],whatsInside:['Custom photo keepsake','Premium envelope','Gift-ready box']},
{id:'a4',slug:'sunday-self-care-edit',name:'Sunday Self-Care Edit',shortDescription:'A slow Sunday, beautifully boxed.',description:'A calming selection for restful rituals and a little everyday indulgence.',sku:'GM-SC-004',price:1799,mrp:2299,stock:12,rating:4.9,reviewCount:102,category:'Self Care',recipients:['For Her','Best Friend'],occasions:['Birthday','Thank You'],badges:['Trending'],personalized:false,color:'#dbe8de',images:['/giftmitra-hero.png'],whatsInside:['Bath salts','Scented candle','Face mask','Herbal tea']},
{id:'a5',slug:'coffee-and-conversations',name:'Coffee & Conversations Box',shortDescription:'Good coffee, warm stories and a gift that lingers.',description:'A charming coffee-led hamper for friends, colleagues and thoughtful thank-yous.',sku:'GM-CC-005',price:1299,mrp:1599,stock:14,rating:4.6,reviewCount:49,category:'Food Hampers',recipients:['For Him','Colleagues'],occasions:['Birthday','Corporate'],badges:['Popular'],personalized:true,color:'#e8ddd2',images:['/giftmitra-hero.png'],whatsInside:['Single-origin coffee','Ceramic mug','Cookies','Gift note']},
{id:'a6',slug:'little-star-celebration-box',name:'Little Star Celebration Box',shortDescription:'A bright bundle of wonder for little stars.',description:'Playful, age-appropriate treats and activities packed with joy.',sku:'GM-LS-006',price:999,mrp:1299,stock:20,rating:4.8,reviewCount:73,category:'Kids Gifts',recipients:['For Kids'],occasions:['Birthday','Congratulations'],badges:['Kids Pick'],personalized:true,color:'#dce9ef',images:['/giftmitra-hero.png'],whatsInside:['Creative activity kit','Healthy treats','Name badge','Celebration card']}
];
export const demoHomepageSections:HomepageSection[]=[{id:'hero',type:'hero_slider',title:'The art of making someone’s day.',subtitle:'The Celebration Edit',enabled:true,sortOrder:1,config:{cta:'/shop'}},{id:'recipient',type:'recipient_collection',title:'Who are you celebrating?',enabled:true,sortOrder:2,config:{}},{id:'trending',type:'product_grid',title:'Trending right now',enabled:true,sortOrder:3,config:{source:'trending'}}];
