create extension if not exists pgcrypto;
create type public.order_status as enum ('pending','payment_pending','paid','confirmed','processing','personalized','packed','shipped','out_for_delivery','delivered','cancelled','return_requested','returned','refund_pending','refunded');
create type public.discount_type as enum ('percentage','fixed');
create type public.payment_status as enum ('pending','authorized','captured','failed','refunded','partially_refunded');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,mobile text unique,email text,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,mobile text not null,alternate_mobile text,line1 text not null,line2 text,landmark text,city text not null,state text not null,postal_code text not null check(postal_code~'^\d{6}$'),country text not null default 'India',address_type text not null default 'home',is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),name text not null unique,description text);
create table public.permissions(id uuid primary key default gen_random_uuid(),key text not null unique,description text);
create table public.role_permissions(role_id uuid references public.roles on delete cascade,permission_id uuid references public.permissions on delete cascade,primary key(role_id,permission_id));
create table public.admin_users(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,role_id uuid not null references public.roles,is_active boolean not null default true,created_at timestamptz not null default now());

create table public.categories(id uuid primary key default gen_random_uuid(),parent_id uuid references public.categories on delete set null,name text not null,slug text not null unique,description text,image_url text,seo_title text,seo_description text,is_active boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.collections(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,description text,image_url text,rules jsonb not null default '{}',is_active boolean not null default true,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.occasions(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,image_url text,is_active boolean not null default true,sort_order int not null default 0);
create table public.recipients(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,image_url text,is_active boolean not null default true,sort_order int not null default 0);
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid references public.categories on delete set null,name text not null,slug text not null unique,short_description text,description text not null default '',rich_content jsonb not null default '{}',sku text not null unique,barcode text,price numeric(12,2) not null check(price>=0),mrp numeric(12,2) not null check(mrp>=price),cost_price numeric(12,2),tax_rate numeric(5,2) not null default 0,stock int not null default 0 check(stock>=0),low_stock_threshold int not null default 5,is_active boolean not null default false,is_featured boolean not null default false,is_personalized boolean not null default false,is_cod_enabled boolean not null default true,rating_average numeric(3,2) not null default 0,rating_count int not null default 0,seo_title text,seo_description text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_media(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,url text not null,media_type text not null check(media_type in('image','video')),alt_text text,sort_order int not null default 0);
create table public.product_variants(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,sku text not null unique,title text not null,options jsonb not null default '{}',price numeric(12,2),mrp numeric(12,2),stock int not null default 0 check(stock>=0),is_active boolean not null default true);
create table public.collection_products(collection_id uuid references public.collections on delete cascade,product_id uuid references public.products on delete cascade,sort_order int not null default 0,primary key(collection_id,product_id));
create table public.product_occasions(product_id uuid references public.products on delete cascade,occasion_id uuid references public.occasions on delete cascade,primary key(product_id,occasion_id));
create table public.product_recipients(product_id uuid references public.products on delete cascade,recipient_id uuid references public.recipients on delete cascade,primary key(product_id,recipient_id));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),variant_id uuid references public.product_variants on delete restrict,product_id uuid references public.products on delete restrict,quantity int not null,reason text not null,reference_type text,reference_id uuid,created_by uuid references auth.users,created_at timestamptz not null default now(),check(variant_id is not null or product_id is not null));

create table public.carts(id uuid primary key default gen_random_uuid(),user_id uuid unique references auth.users on delete cascade,currency text not null default 'INR',gift_note text,gift_wrap boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.cart_items(id uuid primary key default gen_random_uuid(),cart_id uuid not null references public.carts on delete cascade,product_id uuid not null references public.products on delete cascade,variant_id uuid references public.product_variants on delete set null,quantity int not null check(quantity between 1 and 20),personalization jsonb not null default '{}',hamper_configuration jsonb,created_at timestamptz not null default now(),unique(cart_id,product_id,variant_id,personalization));
create table public.wishlists(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users on delete cascade,created_at timestamptz not null default now());
create table public.wishlist_items(wishlist_id uuid references public.wishlists on delete cascade,product_id uuid references public.products on delete cascade,created_at timestamptz not null default now(),primary key(wishlist_id,product_id));
create table public.coupons(id uuid primary key default gen_random_uuid(),code text not null unique,description text,discount_type public.discount_type not null,value numeric(12,2) not null check(value>0),minimum_amount numeric(12,2) not null default 0,maximum_discount numeric(12,2),starts_at timestamptz not null,ends_at timestamptz,total_usage_limit int,usage_per_user int not null default 1,first_order_only boolean not null default false,prepaid_only boolean not null default false,minimum_quantity int not null default 1,applicable_products uuid[] not null default '{}',applicable_categories uuid[] not null default '{}',excluded_products uuid[] not null default '{}',is_active boolean not null default true,created_at timestamptz not null default now());

create sequence public.order_number_seq;
create table public.orders(id uuid primary key default gen_random_uuid(),order_number text not null unique default('GM-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.order_number_seq')::text,6,'0')),user_id uuid not null references auth.users on delete restrict,address_snapshot jsonb not null,status public.order_status not null default 'pending',payment_status public.payment_status not null default 'pending',payment_method text,subtotal numeric(12,2) not null,discount numeric(12,2) not null default 0,shipping numeric(12,2) not null default 0,cod_surcharge numeric(12,2) not null default 0,total numeric(12,2) not null,coupon_code text,gift_note text,preferred_delivery_date date,tracking_url text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders on delete cascade,product_id uuid references public.products on delete restrict,variant_id uuid references public.product_variants on delete restrict,product_snapshot jsonb not null,quantity int not null check(quantity>0),unit_price numeric(12,2) not null,mrp numeric(12,2) not null,personalization jsonb not null default '{}',hamper_configuration jsonb);
create table public.order_status_history(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders on delete cascade,status public.order_status not null,note text,created_by uuid references auth.users,created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders on delete restrict,gateway text not null default 'razorpay',razorpay_order_id text unique,razorpay_payment_id text unique,signature_verified boolean not null default false,status public.payment_status not null default 'pending',method text,amount numeric(12,2) not null,currency text not null default 'INR',gateway_metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.refunds(id uuid primary key default gen_random_uuid(),payment_id uuid not null references public.payments on delete restrict,gateway_refund_id text unique,amount numeric(12,2) not null,status text not null,reason text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.coupon_redemptions(id uuid primary key default gen_random_uuid(),coupon_id uuid not null references public.coupons on delete restrict,user_id uuid not null references auth.users on delete restrict,order_id uuid not null unique references public.orders on delete restrict,discount numeric(12,2) not null,created_at timestamptz not null default now());

create table public.reviews(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,user_id uuid not null references auth.users on delete cascade,order_item_id uuid references public.order_items on delete set null,rating int not null check(rating between 1 and 5),title text not null,body text not null,status text not null default 'pending' check(status in('pending','approved','rejected','hidden')),is_featured boolean not null default false,is_verified_purchase boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(product_id,user_id,order_item_id));
create table public.review_media(id uuid primary key default gen_random_uuid(),review_id uuid not null references public.reviews on delete cascade,url text not null,media_type text not null check(media_type in('image','video')));
create table public.hamper_packaging(id uuid primary key default gen_random_uuid(),name text not null,description text,image_url text,price numeric(12,2) not null,stock int not null default 0,is_active boolean not null default true,sort_order int not null default 0);
create table public.hamper_products(id uuid primary key default gen_random_uuid(),product_id uuid not null unique references public.products on delete cascade,is_active boolean not null default true,sort_order int not null default 0);
create table public.custom_hamper_templates(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users on delete cascade,name text not null,configuration jsonb not null,is_public boolean not null default false,created_at timestamptz not null default now());

create table public.homepage_sections(id uuid primary key default gen_random_uuid(),section_type text not null,title text,subtitle text,description text,cta_label text,cta_url text,desktop_image text,mobile_image text,data_source jsonb not null default '{}',configuration jsonb not null default '{}',is_enabled boolean not null default true,sort_order int not null default 0,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.navigation_items(id uuid primary key default gen_random_uuid(),parent_id uuid references public.navigation_items on delete cascade,label text not null,url text not null,icon text,badge text,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.announcement_bars(id uuid primary key default gen_random_uuid(),text text not null,icon text,url text,starts_at timestamptz,ends_at timestamptz,priority int not null default 0,is_enabled boolean not null default true,background_color text,text_color text);
create table public.banners(id uuid primary key default gen_random_uuid(),title text,subtitle text,desktop_image text not null,mobile_image text,url text,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.testimonials(id uuid primary key default gen_random_uuid(),name text not null,quote text not null,rating int check(rating between 1 and 5),avatar_url text,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.client_logos(id uuid primary key default gen_random_uuid(),name text not null,logo_url text not null,url text,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.corporate_gallery(id uuid primary key default gen_random_uuid(),title text not null,company text,campaign text,description text,image_url text not null,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.corporate_enquiries(id uuid primary key default gen_random_uuid(),company text not null,contact_person text not null,email text not null,phone text not null,quantity int not null,budget numeric(12,2),occasion text,delivery_location text,requirements text,attachment_url text,status text not null default 'new',created_at timestamptz not null default now());
create table public.reels(id uuid primary key default gen_random_uuid(),title text,caption text,video_url text not null,thumbnail_url text,product_id uuid references public.products on delete set null,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.pages(id uuid primary key default gen_random_uuid(),title text not null,slug text not null unique,content jsonb not null default '{}',seo_title text,seo_description text,is_published boolean not null default false,updated_at timestamptz not null default now());
create table public.faqs(id uuid primary key default gen_random_uuid(),question text not null,answer text not null,scope text not null default 'global',scope_id uuid,is_enabled boolean not null default true,sort_order int not null default 0);
create table public.site_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
create table public.theme_settings(id boolean primary key default true check(id),values jsonb not null default '{}',updated_at timestamptz not null default now());
create table public.newsletter_subscribers(id uuid primary key default gen_random_uuid(),email text not null unique,status text not null default 'subscribed',created_at timestamptz not null default now());
create table public.contact_submissions(id uuid primary key default gen_random_uuid(),name text not null,email text not null,phone text,subject text,message text not null,status text not null default 'new',created_at timestamptz not null default now());
create table public.recently_viewed(user_id uuid references auth.users on delete cascade,product_id uuid references public.products on delete cascade,viewed_at timestamptz not null default now(),primary key(user_id,product_id));
create table public.audit_logs(id uuid primary key default gen_random_uuid(),admin_user_id uuid references public.admin_users on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}',ip_hash text,created_at timestamptz not null default now());

create index products_active_idx on public.products(is_active,created_at desc);create index products_category_idx on public.products(category_id);create index variants_product_idx on public.product_variants(product_id);create index orders_user_idx on public.orders(user_id,created_at desc);create index orders_status_idx on public.orders(status,created_at desc);create index reviews_public_idx on public.reviews(product_id,status);create index homepage_order_idx on public.homepage_sections(is_enabled,sort_order);create index audit_entity_idx on public.audit_logs(entity_type,entity_id,created_at desc);

create function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
do $$declare t text;begin foreach t in array array['profiles','addresses','categories','collections','products','carts','orders','payments','reviews','homepage_sections'] loop execute format('create trigger %I_updated before update on public.%I for each row execute function public.set_updated_at()',t,t);end loop;end$$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,mobile,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','GiftMitra Customer'),coalesce(new.raw_user_meta_data->>'mobile',''),new.email);return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;alter table public.addresses enable row level security;alter table public.products enable row level security;alter table public.categories enable row level security;alter table public.collections enable row level security;alter table public.occasions enable row level security;alter table public.recipients enable row level security;alter table public.product_media enable row level security;alter table public.product_variants enable row level security;alter table public.carts enable row level security;alter table public.cart_items enable row level security;alter table public.wishlists enable row level security;alter table public.wishlist_items enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.order_status_history enable row level security;alter table public.payments enable row level security;alter table public.reviews enable row level security;alter table public.review_media enable row level security;alter table public.homepage_sections enable row level security;alter table public.navigation_items enable row level security;alter table public.announcement_bars enable row level security;alter table public.banners enable row level security;alter table public.testimonials enable row level security;alter table public.client_logos enable row level security;alter table public.corporate_gallery enable row level security;alter table public.reels enable row level security;alter table public.pages enable row level security;alter table public.faqs enable row level security;alter table public.newsletter_subscribers enable row level security;alter table public.corporate_enquiries enable row level security;alter table public.contact_submissions enable row level security;

create policy "public active products" on public.products for select using(is_active);create policy "public categories" on public.categories for select using(is_active);create policy "public collections" on public.collections for select using(is_active);create policy "public occasions" on public.occasions for select using(is_active);create policy "public recipients" on public.recipients for select using(is_active);create policy "public media" on public.product_media for select using(exists(select 1 from public.products p where p.id=product_id and p.is_active));create policy "public variants" on public.product_variants for select using(is_active and exists(select 1 from public.products p where p.id=product_id and p.is_active));
create policy "own profile read" on public.profiles for select using(auth.uid()=id);create policy "own profile update" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);create policy "own addresses" on public.addresses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own carts" on public.carts for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own cart items" on public.cart_items for all using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())) with check(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()));create policy "own wishlist" on public.wishlists for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own wishlist items" on public.wishlist_items for all using(exists(select 1 from public.wishlists w where w.id=wishlist_id and w.user_id=auth.uid())) with check(exists(select 1 from public.wishlists w where w.id=wishlist_id and w.user_id=auth.uid()));
create policy "own orders read" on public.orders for select using(auth.uid()=user_id);create policy "own order items read" on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));create policy "own order history read" on public.order_status_history for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));create policy "own payments read" on public.payments for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));create policy "approved reviews public" on public.reviews for select using(status='approved' or auth.uid()=user_id);create policy "submit own review" on public.reviews for insert with check(auth.uid()=user_id);create policy "update pending own review" on public.reviews for update using(auth.uid()=user_id and status='pending') with check(auth.uid()=user_id);create policy "public review media" on public.review_media for select using(exists(select 1 from public.reviews r where r.id=review_id and r.status='approved'));
create policy "public homepage" on public.homepage_sections for select using(is_enabled);create policy "public navigation" on public.navigation_items for select using(is_enabled);create policy "public announcements" on public.announcement_bars for select using(is_enabled);create policy "public banners" on public.banners for select using(is_enabled);create policy "public testimonials" on public.testimonials for select using(is_enabled);create policy "public logos" on public.client_logos for select using(is_enabled);create policy "public gallery" on public.corporate_gallery for select using(is_enabled);create policy "public reels" on public.reels for select using(is_enabled);create policy "public pages" on public.pages for select using(is_published);create policy "public faqs" on public.faqs for select using(is_enabled);create policy "newsletter insert" on public.newsletter_subscribers for insert with check(true);create policy "corporate enquiry insert" on public.corporate_enquiries for insert with check(true);create policy "contact insert" on public.contact_submissions for insert with check(true);

create function public.reserve_inventory(p_order_id uuid,p_lines jsonb) returns void language plpgsql security definer set search_path=public as $$declare line jsonb;begin for line in select * from jsonb_array_elements(p_lines) loop update products set stock=stock-(line->>'quantity')::int where id=(line->>'product_id')::uuid and stock>=(line->>'quantity')::int;if not found then raise exception 'Insufficient inventory';end if;insert into inventory_movements(product_id,quantity,reason,reference_type,reference_id) values((line->>'product_id')::uuid,-(line->>'quantity')::int,'order_paid','order',p_order_id);end loop;end$$;
revoke all on function public.reserve_inventory(uuid,jsonb) from public,anon,authenticated;

insert into public.roles(name,description) values('SUPER_ADMIN','Full platform access'),('ADMIN','General administration'),('PRODUCT_MANAGER','Products and inventory'),('ORDER_MANAGER','Orders and fulfilment'),('CONTENT_MANAGER','CMS and media'),('SUPPORT','Customers and reviews');
insert into public.permissions(key,description) values('products.write','Manage products'),('orders.write','Manage orders'),('content.write','Manage CMS'),('users.read','View customers'),('settings.write','Manage settings'),('roles.write','Manage admin roles');
